courseview/config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get 'courses/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :course, only: [:index]
  root to: 'courses#index'
end

courseview/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

courseview/app/models/course.rb
class Course < ApplicationRecord
	include PgSearch
	pg_search_scope :search_by_course, against: [:title, :courseNumber],
	using: {
	  tsearch: {
	    prefix: true,
	    negation: true,
	    highlight: {
	        start_sel: '<b>',
	        stop_sel: '</b>',
		}
	  }
	}
end

courseview/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

courseview/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    if params[:term].present?
      @courses = Course.search_by_course(params[:term])
    else
      @courses = Course.all
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.fetch(:course, {})
    end
end

courseview/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
	@courses = Course.all
	if params[:term]
  		@courses = Course.search_by_course(params[:term])
  	end
  end
end

courseview/app/helpers/application_helper.rb
module ApplicationHelper
end

courseview/app/helpers/courses_helper.rb
module CoursesHelper
end

courseview/app/helpers/main_helper.rb
module MainHelper
end

courseview/app/views/courses/_course.html.erb
test

courseview/app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

courseview/app/views/courses/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
      <a class="navbar-brand" href="#">
	    <img src="/assets/images/harvard_icon.png" width="30" height="30" class="d-inline-block align-top" alt="">
	    Planner, Fall 2017
	  </a>
  </div>
</nav>

courseview/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

courseview/app/views/courses/index.html.erb
<%= render "navbar" %>


<div class="col-md-8" id="left-panel">
  <h1>Main#index</h1>
  <p>Find me in app/views/main/index.html.erb testest</p>

  <ul>
    <%= render "course" %>
  </ul>

</div>


<div class="col-md-4" id="right-panel">
  <div class="input-group form-group">
    <%= form_tag courses_index_path, id: "search-form", method: :get do %>
    <%= text_field_tag 'term', params[:term], placeholder: "Course name/number", :class => 'form-control', id:'searchbar' %>
    <span class="input-group-btn">
      <%= submit_tag 'Search', class: 'btn btn-default' %>
    </span>
    <% end %>
  </div>

  <% @courses.each do |c| %>
  <%= c.title %><br>
  <% end %>

</div>

courseview/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

courseview/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

courseview/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Courseview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

courseview/app/views/main/index.html.erb
main